spring:
  application:
    name: jjl-housekeeping
  datasource:
    url: jdbc:postgresql://localhost:5432/jjl_housekeeping
    username: postgres
    password: 123456
  servlet:
    multipart:
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 100MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

logging:
  level:
    cn.lkgc.jjl.dal.*: debug

cors:
  allow-origins:
    - http://localhost:5173

server:
  host: http://localhost
  port: 8080

resources:
  avatarPath: D:/upload/avatar
  carouselPath: D:/upload/carousel
  picturePath: D:/upload/picture
  editorImagePath: D:/upload/editor/image
  editorVideoPath: D:/upload/editor/video
  path-patterns:
    - /resources/**
  locations:
    - file:D:/upload/
